### ISSUE TITLE
The split screen preview should match the scroll position of the editor.

### ISSUE THREAD

**Issue by PeterHindes** [wbrawner/SimpleMarkdown#102] opened 2024-12-30 00:42 UTC
Editing while using the preview, or even while switching between the two in portrait editing should scroll to the place where the cursor is in the editor to make it easier to see what you are doing.

_Originally posted by @PeterHindes in https://github.com/wbrawner/SimpleMarkdown/issues/94#issuecomment-2564888764_

**Comment by wbrawner** [comment] 2024-12-30 01:00
I'm going to close this as a duplicate of #67, but it's on my radar. Haven't found the time to look into it yet but I've got some local changes that might make this easier. Keep an eye on this space

**Closed** 2024-12-30 01:00 UTC
